In [1]:
import pandas as pd
import xlwings as xw
import os

os.chdir(r"P:/Intel 자동화 검증")
bk1 = xw.Book('03W105MR3 data.xlsx')

In [2]:
path_fname = 'P:/Intel 자동화 검증/03W105MR3 data.xlsx'
# print(path_fname.split('.')[-2])
print(os.path.basename(path_fname).split('.')[0].split(' ')[0])

03W105MR3


In [3]:
sh1 = bk1.sheets(1)
sh1.name

'AI9MP1U_3X4'

In [4]:
sh2 = bk1.sheets(2)
sh2.name

'AI9MP1U_3X4_2'

In [5]:
sh3 = bk1.sheets(3)
sh3.name

'AI9MP1X_3X4'

In [6]:
sh4 = bk1.sheets(4)
sh4.name

'AI9MP1X_3X4_2'

In [7]:
df1_des = sh1.range('B3:B13').options(pd.DataFrame, index=False, header=False, expand='right').value

# df1_des = bk1.sheets(1).range('B3:M13').options(pd.DataFrame, index=False, header=False).value

#df1 = bk1.sheets(1).used_range.options(pd.DataFrame, index=False, header=False).value
#df1 = sh1.range('A1').options(pd.DataFrame, index=False, header=False, expand='table').value
#df1 = df1.astype('float')
df1_des.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 12 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   0       11 non-null     object
 1   1       11 non-null     object
 2   2       11 non-null     object
 3   3       11 non-null     object
 4   4       11 non-null     object
 5   5       11 non-null     object
 6   6       11 non-null     object
 7   7       11 non-null     object
 8   8       11 non-null     object
 9   9       11 non-null     object
 10  10      11 non-null     object
 11  11      11 non-null     object
dtypes: object(12)
memory usage: 1.2+ KB


In [8]:
df1_des

0             1             2             3           4   \
0         1904.0        1905.0        1906.0        1907.0      1915.0   
1       221220.0      221220.0      221220.0      221220.0    230101.0   
2   12/29(18:00)  12/29(18:00)  12/29(18:00)  12/29(18:00)  1/3(14:30)   
3       181835.0      181835.0      181835.0      181835.0    143250.0   
4            1-1           1-1           1-1           1-1         1-2   
5       03W105MQ      03W105MQ      03W105MQ      03W105MQ    03W105MQ   
6        AI9MP1U       AI9MP1U       AI9MP1U       AI9MP1U     AI9MP1U   
7           40.0          40.0          40.0          40.0        40.0   
8          105.0         105.0         105.0         105.0       115.0   
9           12.0          14.0          16.0          18.0        12.0   
10         300.0         300.0         300.0         300.0       200.0   

            5           6           7             8             9   \
0       1916.0      1917.0      1918.0        1842.0        1843.0   
1     230101.0    230101.0    230101.0      221212.0      221212.0   
2   1/3(14:30)  1/3(14:30)  1/3(14:30)  12/12(09:10)  12/12(09:10)   
3     143250.0    143250.0    143250.0      173230.0      173230.0   
4          1-2         1-2         1-2           1-1           1-1   
5     03W105MQ    03W105MQ    03W105MQ      03W205MS      03W205MS   
6      AI9MP1U     AI9MP1U     AI9MP1U       AI9MP1U       AI9MP1U   
7         40.0        40.0        40.0          40.0          40.0   
8        115.0       115.0       115.0         125.0         125.0   
9         14.0        16.0        18.0          12.0          14.0   
10       200.0       200.0       200.0         120.0         120.0   

              10            11  
0         1844.0        1845.0  
1       221212.0      221212.0  
2   12/12(09:10)  12/12(09:10)  
3       173230.0      173230.0  
4            1-1           1-1  
5       03W205MS      03W205MS  
6        AI9MP1U       AI9MP1U  
7           40.0          40.0  
8          125.0         125.0  
9           16.0          18.0  
10         120.0         120.0

In [9]:
time = df1_des.iloc[10].to_list()
temp = df1_des.iloc[8].to_list()
volt = df1_des.iloc[9].to_list()
quantity = df1_des.iloc[7].to_list()

column = [str(int(temp[i])) + '-' + str(float(volt[i])) for i in range(len(temp))]
print(temp, volt, quantity, time, column)  

# [x+y for x,y in zip(list1, list2)]

# df1_des.loc[12] = column
# df1_des

[105.0, 105.0, 105.0, 105.0, 115.0, 115.0, 115.0, 115.0, 125.0, 125.0, 125.0, 125.0] [12.0, 14.0, 16.0, 18.0, 12.0, 14.0, 16.0, 18.0, 12.0, 14.0, 16.0, 18.0] [40.0, 40.0, 40.0, 40.0, 40.0, 40.0, 40.0, 40.0, 40.0, 40.0, 40.0, 40.0] [300.0, 300.0, 300.0, 300.0, 200.0, 200.0, 200.0, 200.0, 120.0, 120.0, 120.0, 120.0] ['105-12.0', '105-14.0', '105-16.0', '105-18.0', '115-12.0', '115-14.0', '115-16.0', '115-18.0', '125-12.0', '125-14.0', '125-16.0', '125-18.0']


In [10]:
print(type(column), type(column[0]))

<class 'list'> <class 'str'>


In [11]:
df1_data = sh1.range('B14').options(pd.DataFrame, index=False, header=False, expand='table').value
# ※header에 cloumn 사용 시 type error

#df1 = bk1.sheets(1).used_range.options(pd.DataFrame, index=False, header=False).value
#sht.range('A1').options(pd.DataFrame, index=False, header=False, expand='table').value
#df1 = df1.astype('float')

df1_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 12 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   0       40 non-null     float64
 1   1       40 non-null     float64
 2   2       40 non-null     float64
 3   3       40 non-null     float64
 4   4       40 non-null     float64
 5   5       40 non-null     float64
 6   6       40 non-null     float64
 7   7       40 non-null     float64
 8   8       40 non-null     float64
 9   9       40 non-null     float64
 10  10      40 non-null     float64
 11  11      40 non-null     float64
dtypes: float64(12)
memory usage: 3.9 KB


In [12]:
df1_data.astype('float')

df1_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 12 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   0       40 non-null     float64
 1   1       40 non-null     float64
 2   2       40 non-null     float64
 3   3       40 non-null     float64
 4   4       40 non-null     float64
 5   5       40 non-null     float64
 6   6       40 non-null     float64
 7   7       40 non-null     float64
 8   8       40 non-null     float64
 9   9       40 non-null     float64
 10  10      40 non-null     float64
 11  11      40 non-null     float64
dtypes: float64(12)
memory usage: 3.9 KB


In [13]:
df1_data


0           1           2          3           4          5   \
0   999.000000    0.000000    2.141667   5.878333    7.505556   6.697222   
1   999.000000    0.000000    6.798333  12.206111   12.831944  13.416944   
2   999.000000    7.586111   10.521667  12.361389   20.620556  14.573056   
3   999.000000   26.356111   14.483889  14.218333   21.730278  15.325000   
4   999.000000   39.881944   14.641667  15.978333   25.033889  19.062222   
5   999.000000   65.559722   16.621389  17.637778   27.413889  19.784167   
6   999.000000   69.103889   16.649167  18.280278   29.061944  21.216944   
7   999.000000   74.503333   18.910556  19.799167   39.038333  22.710833   
8   999.000000   89.236667   19.386111  22.440278   39.536667  23.541111   
9   999.000000   90.392500   24.159444  22.548889   46.926389  26.313056   
10   26.219722   92.561667   25.018333  23.802778   48.050278  27.507500   
11   45.566944   93.789722   26.989722  24.697778   50.406111  28.369167   
12   52.091667   96.221667   28.326944  25.336111   52.086389  29.094444   
13   89.267222  107.787778   28.426111  25.882500   56.428611  29.677222   
14   97.090278  108.685833   38.143611  28.801667   61.230000  29.846389   
15  100.894444  108.729444   49.500278  30.051111   61.277222  32.081389   
16  114.363333  116.736944   52.075278  30.636667   62.152500  33.780278   
17  115.580556  117.981389   53.609444  30.725000   66.688056  35.324444   
18  117.031944  122.366667   56.949444  31.514167   67.742778  35.420556   
19  130.772778  134.065278   57.058889  32.043333   71.355556  35.796667   
20  133.171389  142.020278   62.821389  33.023889   73.320833  36.766389   
21  169.758056  144.908889   63.143611  34.793056   79.486111  37.152500   
22  171.551389  145.921667   64.589444  36.996944   83.194167  38.721389   
23  180.357222  147.216667   66.554167  37.335000   83.966667  40.108056   
24  183.062222  149.974167   71.355556  37.971667   87.289444  40.653889   
25  189.014722  150.592222   74.155000  38.048056   95.853056  40.931944   
26  189.328611  152.580000   74.460278  39.546667   99.539722  41.093333   
27  189.721111  153.336667   75.998056  40.316389  100.636944  41.121667   
28  192.216389  159.781667   78.580000  43.739444  101.293889  48.505833   
29  203.994444  174.993056   79.895278  46.178056  101.377500  48.930833   
30  211.456389  190.176667   81.946389  46.738889  103.483611  49.905833   
31  245.244444  202.134167   83.403333  49.125556  103.880833  50.258611   
32  250.507222  203.611111   87.452222  49.714167  104.292778  51.766389   
33  252.951389  207.163611   88.105000  50.611111  108.316667  54.817222   
34  255.568889  210.456944   88.387500  51.895833  111.427222  58.169722   
35  267.528333  216.811111  100.885278  58.203889  115.325278  66.849722   
36  271.252222  229.823056  103.942222  59.451111  137.757500  67.828889   
37  275.146667  241.203333  112.787500  62.052500  138.809722  75.528056   
38  288.141111  247.965556  131.104167  64.922222  140.894444  84.371111   
39  298.299444  258.360000  141.128333  67.656667  142.445556  99.383333   

           6          7      8      9      10     11  
0    0.518611   0.614167  62.47  15.37  12.15   7.78  
1    2.605278   1.490556  57.72   9.40   8.72   0.70  
2    2.643056   1.658056  28.07   3.28   3.90   5.48  
3    3.063056   1.807500  17.67  12.51   6.20   4.64  
4    4.183611   4.088611  44.38  17.52   5.80   7.37  
5    4.518611   4.967778  10.04  17.32   3.19   8.01  
6    5.764722   5.440278  11.64   6.41   7.73   5.61  
7    5.951944   5.838889  50.32  14.28   9.99   2.78  
8   10.319167   6.313889  36.03  21.05  11.13   4.78  
9   10.550833   7.250278  38.89  18.77  18.53   0.91  
10  10.950000   7.640833  30.02   9.30   1.27   5.75  
11  11.306667   8.288056  11.38  27.26   8.43   3.84  
12  11.879722   9.038333  24.04   7.02   7.13   1.42  
13  12.391111  10.239167  11.49  19.08   9.02   7.03  
14  12.985000  10.582222  22.57  13.50  15.93   0.01  
15  13.244167  

In [14]:
# 시험온도, 시험전압 테이블 추출
test_temp = list(set(temp))
#print(temp, test_temp)
test_temp = [int(x) for x in test_temp if pd.isnull(x) == False]
test_temp.sort()
#print(test_temp)
test_temp = [str(x) for x in test_temp if pd.isnull(x) == False]
print(test_temp)

test_volt = list(set(volt))
test_volt = [float(x) for x in test_volt if pd.isnull(x) == False]
test_volt.sort()
test_volt = [str(x) for x in test_volt if pd.isnull(x) == False]
print(test_volt)

# 테스트 수량 추출
test_quantity = list(set(quantity))
#print(temp, test_temp)
test_quantity = [int(x) for x in test_quantity if pd.isnull(x) == False]
#test_quantity.sort()

max_quantity = max(test_quantity)
print(max_quantity)

test_time = time
print(test_time)

['105', '115', '125']
['12.0', '14.0', '16.0', '18.0']
40
[300.0, 300.0, 300.0, 300.0, 200.0, 200.0, 200.0, 200.0, 120.0, 120.0, 120.0, 120.0]


In [15]:
show_data = df1_data.copy()     # df1_data에 show_data 변경이 반영되지 않음. 깊은 복사
show_data = show_data.round(2)  # show 에서만 round 처리 / pandasModel에서 처리
show_data.columns = column

new_index = range(1,max_quantity+1)
show_data.index = new_index

show_data

105-12.0  105-14.0  105-16.0  105-18.0  115-12.0  115-14.0  115-16.0  \
1     999.00      0.00      2.14      5.88      7.51      6.70      0.52   
2     999.00      0.00      6.80     12.21     12.83     13.42      2.61   
3     999.00      7.59     10.52     12.36     20.62     14.57      2.64   
4     999.00     26.36     14.48     14.22     21.73     15.32      3.06   
5     999.00     39.88     14.64     15.98     25.03     19.06      4.18   
6     999.00     65.56     16.62     17.64     27.41     19.78      4.52   
7     999.00     69.10     16.65     18.28     29.06     21.22      5.76   
8     999.00     74.50     18.91     19.80     39.04     22.71      5.95   
9     999.00     89.24     19.39     22.44     39.54     23.54     10.32   
10    999.00     90.39     24.16     22.55     46.93     26.31     10.55   
11     26.22     92.56     25.02     23.80     48.05     27.51     10.95   
12     45.57     93.79     26.99     24.70     50.41     28.37     11.31   
13     52.09     96.22     28.33     25.34     52.09     29.09     11.88   
14     89.27    107.79     28.43     25.88     56.43     29.68     12.39   
15     97.09    108.69     38.14     28.80     61.23     29.85     12.98   
16    100.89    108.73     49.50     30.05     61.28     32.08     13.24   
17    114.36    116.74     52.08     30.64     62.15     33.78     13.84   
18    115.58    117.98     53.61     30.72     66.69     35.32     14.54   
19    117.03    122.37     56.95     31.51     67.74     35.42     16.27   
20    130.77    134.07     57.06     32.04     71.36     35.80     17.37   
21    133.17    142.02     62.82     33.02     73.32     36.77     18.40   
22    169.76    144.91     63.14     34.79     79.49     37.15     19.11   
23    171.55    145.92     64.59     37.00     83.19     38.72     19.82   
24    180.36    147.22     66.55     37.34     83.97     40.11     21.04   
25    183.06    149.97     71.36     37.97     87.29     40.65     21.70   
26    189.01    150.59     74.16     38.05     95.85     40.93     22.06   
27    189.33    152.58     74.46     39.55     99.54     41.09     23.47   
28    189.72    153.34     76.00     40.32    100.64     41.12     25.27   
29    192.22    159.78     78.58     43.74    101.29     48.51     25.96   
30    203.99    174.99     79.90     46.18    101.38     48.93     26.60   
31    211.46    190.18     81.95     46.74    103.48     49.91     26.71   
32    245.24    202.13     83.40     49.13    103.88     50.26     26.94   
33    250.51    203.61     87.45     49.71    104.29     51.77     26.94   
34    252.95    207.16     88.10     50.61    108.32     54.82     27.00   
35    255.57    210.46     88.39     51.90    111.43     58.17     27.52   
36    267.53    216.81    100.89     58.20    115.33     66.85     27.59   
37    271.25    229.82    103.94     59.45    137.76     67.83     28.20   
38    275.15    241.20    112.79     62.05    138.81     75.53     29.39   
39    288.14    247.97    131.10     64.92    140.89     84.37     32.55   
40    298.30    258.36    141.13     67.66    142.45     99.38     33.14   

    115-18.0  125-12.0  125-14.0  125-16.0  125-18.0  
1       0.61     62.47     15.37     12.15      7.78  
2       1.49     57.72      9.40      8.72      0.70  
3       1.66     28.07      3.28      3.90      5.48  
4       1.81     17.67     12.51      6.20      4.64  
5       4.09     44.38     17.52      5.80      7.37  
6       4.97     10.04     17.32      3.19      8.01  
7       5.44     11.64      6.41      7.73      5.61  
8       5.84     50.32     14.28      9.99      2.78  
9       6.31     36.03     21.05     11.13      4.78  
10      7.25     38.89     18.77     18.53      0.91  
11      7.64     30.02      9.30      1.27      5.75  
12      8.29     11.38     27.26      8.43      3.84  
13      9.04     24.04      7.02      7.13      1.42  
14     10.24     11.49     19.08      9.02      7.03  
15     10.58     22.57     13.50     15.93      0.01  
16     

In [16]:
testcond = pd.DataFrame(columns = test_volt, index = test_temp)
print(testcond)

    12.0 14.0 16.0 18.0
105  NaN  NaN  NaN  NaN
115  NaN  NaN  NaN  NaN
125  NaN  NaN  NaN  NaN


In [17]:
testcond = testcond.fillna('V')
print(testcond)             
#bike_data.loc[bike_data.Gender.isnull(), 'Gender'] = 'U'

    12.0 14.0 16.0 18.0
105    V    V    V    V
115    V    V    V    V
125    V    V    V    V


In [18]:
print(type(test_temp), type(test_temp[0]))

<class 'list'> <class 'str'>


In [19]:
import numpy as np

max_data = max_quantity
i = len(test_temp)
j = len(test_volt)
k = max_data

data_array= np.zeros((i, j, k))

count=0
for x in range(len(test_temp)):
    for y in range(len(test_volt)):
        data_array[x][y] = df1_data.loc[0:39, count]
        data_array[x][y] = sorted(data_array[x][y])
        count += 1   
        
#for x in range(len(column)):
#    df1_data[x] = df1_data[x].apply(lambda r: f'{np.round(r, decimals=1):.1f}')

#df1_data
        
print(data_array, type(data_array), type(data_array[0][0][0]))

[[[2.62197222e+01 4.55669444e+01 5.20916667e+01 8.92672222e+01
   9.70902778e+01 1.00894444e+02 1.14363333e+02 1.15580556e+02
   1.17031944e+02 1.30772778e+02 1.33171389e+02 1.69758056e+02
   1.71551389e+02 1.80357222e+02 1.83062222e+02 1.89014722e+02
   1.89328611e+02 1.89721111e+02 1.92216389e+02 2.03994444e+02
   2.11456389e+02 2.45244444e+02 2.50507222e+02 2.52951389e+02
   2.55568889e+02 2.67528333e+02 2.71252222e+02 2.75146667e+02
   2.88141111e+02 2.98299444e+02 9.99000000e+02 9.99000000e+02
   9.99000000e+02 9.99000000e+02 9.99000000e+02 9.99000000e+02
   9.99000000e+02 9.99000000e+02 9.99000000e+02 9.99000000e+02]
  [0.00000000e+00 0.00000000e+00 7.58611111e+00 2.63561111e+01
   3.98819444e+01 6.55597222e+01 6.91038889e+01 7.45033333e+01
   8.92366667e+01 9.03925000e+01 9.25616667e+01 9.37897222e+01
   9.62216667e+01 1.07787778e+02 1.08685833e+02 1.08729444e+02
   1.16736944e+02 1.17981389e+02 1.22366667e+02 1.34065278e+02
   1.42020278e+02 1.44908889e+02 1.45921667e+02 1.4721

In [20]:
print(list(range(len(test_temp))))

[0, 1, 2]


In [21]:
from itertools import combinations, product

temp_comb = list(combinations(list(range(len(test_temp))), 2))
volt_comb = list(combinations(list(range(len(test_volt))), 2))

unit_comb = list(product(temp_comb,volt_comb))

print(temp_comb)
print(volt_comb)
print(unit_comb)

[(0, 1), (0, 2), (1, 2)]
[(0, 1), (0, 2), (0, 3), (1, 2), (1, 3), (2, 3)]
[((0, 1), (0, 1)), ((0, 1), (0, 2)), ((0, 1), (0, 3)), ((0, 1), (1, 2)), ((0, 1), (1, 3)), ((0, 1), (2, 3)), ((0, 2), (0, 1)), ((0, 2), (0, 2)), ((0, 2), (0, 3)), ((0, 2), (1, 2)), ((0, 2), (1, 3)), ((0, 2), (2, 3)), ((1, 2), (0, 1)), ((1, 2), (0, 2)), ((1, 2), (0, 3)), ((1, 2), (1, 2)), ((1, 2), (1, 3)), ((1, 2), (2, 3))]


In [22]:
for i in range(len(temp_comb)):
    print(test_temp[temp_comb[i][0]], test_temp[temp_comb[i][1]])

print('\n')
    
for i in range(len(volt_comb)):
    print(test_volt[volt_comb[i][0]], test_volt[volt_comb[i][1]])

print('\n')
print('temp_subset    /    volt_subset')

print(len(unit_comb), unit_comb[0][0], unit_comb[0][1])

105 115
105 125
115 125


12.0 14.0
12.0 16.0
12.0 18.0
14.0 16.0
14.0 18.0
16.0 18.0


temp_subset    /    volt_subset
18 (0, 1) (0, 1)


In [23]:
for i in range(len(unit_comb)):
    print(unit_comb[i][0], unit_comb[i][1]) 

print('\n')
print('temp_unitset    /    volt_unitset')

for i in range(len(unit_comb)):
    #for j in range(0,1):
        print(test_temp[unit_comb[i][0][0]], '-', test_temp[unit_comb[i][0][1]], ' / ', test_volt[unit_comb[i][1][0]], '-', test_volt[unit_comb[i][1][1]])

(0, 1) (0, 1)
(0, 1) (0, 2)
(0, 1) (0, 3)
(0, 1) (1, 2)
(0, 1) (1, 3)
(0, 1) (2, 3)
(0, 2) (0, 1)
(0, 2) (0, 2)
(0, 2) (0, 3)
(0, 2) (1, 2)
(0, 2) (1, 3)
(0, 2) (2, 3)
(1, 2) (0, 1)
(1, 2) (0, 2)
(1, 2) (0, 3)
(1, 2) (1, 2)
(1, 2) (1, 3)
(1, 2) (2, 3)


temp_unitset    /    volt_unitset
105 - 115  /  12.0 - 14.0
105 - 115  /  12.0 - 16.0
105 - 115  /  12.0 - 18.0
105 - 115  /  14.0 - 16.0
105 - 115  /  14.0 - 18.0
105 - 115  /  16.0 - 18.0
105 - 125  /  12.0 - 14.0
105 - 125  /  12.0 - 16.0
105 - 125  /  12.0 - 18.0
105 - 125  /  14.0 - 16.0
105 - 125  /  14.0 - 18.0
105 - 125  /  16.0 - 18.0
115 - 125  /  12.0 - 14.0
115 - 125  /  12.0 - 16.0
115 - 125  /  12.0 - 18.0
115 - 125  /  14.0 - 16.0
115 - 125  /  14.0 - 18.0
115 - 125  /  16.0 - 18.0


In [24]:
no_of_comb = len(temp_comb)*len(volt_comb)
comb_3_cond = np.zeros((no_of_comb*4, 3, max_quantity))
ret = np.zeros((no_of_comb, 4, 3, 2))

print(comb_3_cond, '\n\n', ret)

[[[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 ...

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]] 

 [[[[0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]]]


 [[[0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]]]


 [[[0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]]]


 [[[0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [

In [25]:
for i in range(0, no_of_comb):
    tot_set = list(product(unit_comb[i][0], unit_comb[i][1]))
    final_comb = list(combinations(tot_set, 3))
    print(final_comb)
    ret[i] = np.array(final_comb)
    
#print(type(final_comb), final_comb)
# 변수명 수정 : last_last → final_comb
print(type(ret), type(ret[0]), type(ret[0][0]), type(ret[0][0][0]), type(ret[0][0][0][0]), '\n', ret)

[((0, 0), (0, 1), (1, 0)), ((0, 0), (0, 1), (1, 1)), ((0, 0), (1, 0), (1, 1)), ((0, 1), (1, 0), (1, 1))]
[((0, 0), (0, 2), (1, 0)), ((0, 0), (0, 2), (1, 2)), ((0, 0), (1, 0), (1, 2)), ((0, 2), (1, 0), (1, 2))]
[((0, 0), (0, 3), (1, 0)), ((0, 0), (0, 3), (1, 3)), ((0, 0), (1, 0), (1, 3)), ((0, 3), (1, 0), (1, 3))]
[((0, 1), (0, 2), (1, 1)), ((0, 1), (0, 2), (1, 2)), ((0, 1), (1, 1), (1, 2)), ((0, 2), (1, 1), (1, 2))]
[((0, 1), (0, 3), (1, 1)), ((0, 1), (0, 3), (1, 3)), ((0, 1), (1, 1), (1, 3)), ((0, 3), (1, 1), (1, 3))]
[((0, 2), (0, 3), (1, 2)), ((0, 2), (0, 3), (1, 3)), ((0, 2), (1, 2), (1, 3)), ((0, 3), (1, 2), (1, 3))]
[((0, 0), (0, 1), (2, 0)), ((0, 0), (0, 1), (2, 1)), ((0, 0), (2, 0), (2, 1)), ((0, 1), (2, 0), (2, 1))]
[((0, 0), (0, 2), (2, 0)), ((0, 0), (0, 2), (2, 2)), ((0, 0), (2, 0), (2, 2)), ((0, 2), (2, 0), (2, 2))]
[((0, 0), (0, 3), (2, 0)), ((0, 0), (0, 3), (2, 3)), ((0, 0), (2, 0), (2, 3)), ((0, 3), (2, 0), (2, 3))]
[((0, 1), (0, 2), (2, 1)), ((0, 1), (0, 2), (2, 2)), ((

In [26]:
print(type(final_comb))
#com_3_cond = d
for i in range(0,2):
    print(final_comb[0][i])
    
    
    
for i in range(0,18):
    print(test_temp[unit_comb[i][0][0]], '-', test_temp[unit_comb[i][0][1]], ' / ', test_volt[unit_comb[i][1][0]], '-', test_volt[unit_comb[i][1][1]])

<class 'list'>
(1, 2)
(1, 3)
105 - 115  /  12.0 - 14.0
105 - 115  /  12.0 - 16.0
105 - 115  /  12.0 - 18.0
105 - 115  /  14.0 - 16.0
105 - 115  /  14.0 - 18.0
105 - 115  /  16.0 - 18.0
105 - 125  /  12.0 - 14.0
105 - 125  /  12.0 - 16.0
105 - 125  /  12.0 - 18.0
105 - 125  /  14.0 - 16.0
105 - 125  /  14.0 - 18.0
105 - 125  /  16.0 - 18.0
115 - 125  /  12.0 - 14.0
115 - 125  /  12.0 - 16.0
115 - 125  /  12.0 - 18.0
115 - 125  /  14.0 - 16.0
115 - 125  /  14.0 - 18.0
115 - 125  /  16.0 - 18.0


In [27]:
output_array = np.zeros((no_of_comb, 4, 3, max_quantity))

for i in range(0,no_of_comb):
    for j in range(0,4):
        for k in range(0,3):
            #comb_data = data_array[final_comb[i][j][k][0]][final_comb[i][j][k][1]]
            output_array[i][j][k] = data_array[int(ret[i][j][k][0])][int(ret[i][j][k][1])]
            #print(comb_data)

print(output_array)

[[[[2.62197222e+01 4.55669444e+01 5.20916667e+01 ... 9.99000000e+02
    9.99000000e+02 9.99000000e+02]
   [0.00000000e+00 0.00000000e+00 7.58611111e+00 ... 2.41203333e+02
    2.47965556e+02 2.58360000e+02]
   [7.50555556e+00 1.28319444e+01 2.06205556e+01 ... 1.38809722e+02
    1.40894444e+02 1.42445556e+02]]

  [[2.62197222e+01 4.55669444e+01 5.20916667e+01 ... 9.99000000e+02
    9.99000000e+02 9.99000000e+02]
   [0.00000000e+00 0.00000000e+00 7.58611111e+00 ... 2.41203333e+02
    2.47965556e+02 2.58360000e+02]
   [6.69722222e+00 1.34169444e+01 1.45730556e+01 ... 7.55280556e+01
    8.43711111e+01 9.93833333e+01]]

  [[2.62197222e+01 4.55669444e+01 5.20916667e+01 ... 9.99000000e+02
    9.99000000e+02 9.99000000e+02]
   [7.50555556e+00 1.28319444e+01 2.06205556e+01 ... 1.38809722e+02
    1.40894444e+02 1.42445556e+02]
   [6.69722222e+00 1.34169444e+01 1.45730556e+01 ... 7.55280556e+01
    8.43711111e+01 9.93833333e+01]]

  [[0.00000000e+00 0.00000000e+00 7.58611111e+00 ... 2.41203333e+02

In [28]:
# temp = df1_des.iloc[8].to_list()
# volt = df1_des.iloc[9].to_list()
# quantity = df1_des.iloc[7].to_list()
# time = df1_des.iloc[10].to_list()

# column = [str(int(temp[i])) + '-' + str(float(volt[i])) for i in range(len(temp))]
# # [x+y for x,y in zip(list1, list2)]
# print(temp, volt, quantity, time, column)


# output
# [125.0, 125.0, 125.0, 125.0, 135.0, 135.0, 135.0, 135.0, 145.0, 145.0, 145.0, 145.0]
# [12.0, 14.0, 16.0, 18.0, 12.0, 14.0, 16.0, 18.0, 12.0, 14.0, 16.0, 18.0]
# [40.0, 40.0, 40.0, 40.0, 40.0, 40.0, 40.0, 40.0, 40.0, 40.0, 40.0, 40.0] 
# [200.0, 200.0, 200.0, 200.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0] 
# ['125-12.0', '125-14.0', '125-16.0', '125-18.0', '135-12.0', '135-14.0', '135-16.0', '135-18.0', '145-12.0', '145-14.0', '145-16.0', '145-18.0']


# title_array2 = np.zeros((72, 3, 2))

title_array=[] 
title_array2=[]

print(type(title_array2), title_array2)

for i in range(0,no_of_comb):
    for j in range(0,4):
        for k in range(0,3):
            title_array.append(test_temp[int(ret[i][j][k][0])] + '-' + test_volt[int(ret[i][j][k][1])]) 
 
print(title_array)    

# Array로 수정
for i in range(0, no_of_comb*4*3, 3):
    title_array2.append(title_array[i] + '/' + title_array[i+1] + '/' + title_array[i+2]) 
    
# for i in range(0, 18*4*3, 3):
#     title_array2.append(title_array[i] + '/' + title_array[i+1] + '/' + title_array[i+2]) 
    
print(title_array2)    

# for i in range(0, 18*4*3):
#     print(title_array[i])

<class 'list'> []
['105-12.0', '105-14.0', '115-12.0', '105-12.0', '105-14.0', '115-14.0', '105-12.0', '115-12.0', '115-14.0', '105-14.0', '115-12.0', '115-14.0', '105-12.0', '105-16.0', '115-12.0', '105-12.0', '105-16.0', '115-16.0', '105-12.0', '115-12.0', '115-16.0', '105-16.0', '115-12.0', '115-16.0', '105-12.0', '105-18.0', '115-12.0', '105-12.0', '105-18.0', '115-18.0', '105-12.0', '115-12.0', '115-18.0', '105-18.0', '115-12.0', '115-18.0', '105-14.0', '105-16.0', '115-14.0', '105-14.0', '105-16.0', '115-16.0', '105-14.0', '115-14.0', '115-16.0', '105-16.0', '115-14.0', '115-16.0', '105-14.0', '105-18.0', '115-14.0', '105-14.0', '105-18.0', '115-18.0', '105-14.0', '115-14.0', '115-18.0', '105-18.0', '115-14.0', '115-18.0', '105-16.0', '105-18.0', '115-16.0', '105-16.0', '105-18.0', '115-18.0', '105-16.0', '115-16.0', '115-18.0', '105-18.0', '115-16.0', '115-18.0', '105-12.0', '105-14.0', '125-12.0', '105-12.0', '105-14.0', '125-14.0', '105-12.0', '125-12.0', '125-14.0', '105-14.0

In [29]:
# ***************** 여기부터 *****************
reduction = np.reshape(output_array, (no_of_comb*4, 3, -1))
print (output_array.shape, reduction.shape)

# 결과가 길어서 주석 처리 결과 확인하려면 주석 삭제 
for i in range(0, no_of_comb*4):
    for j in range(0, 3):
        #for k in range(0, 40):
            print(reduction[i][j])

(18, 4, 3, 40) (72, 3, 40)
[ 26.21972222  45.56694444  52.09166667  89.26722222  97.09027778
 100.89444444 114.36333333 115.58055556 117.03194444 130.77277778
 133.17138889 169.75805556 171.55138889 180.35722222 183.06222222
 189.01472222 189.32861111 189.72111111 192.21638889 203.99444444
 211.45638889 245.24444444 250.50722222 252.95138889 255.56888889
 267.52833333 271.25222222 275.14666667 288.14111111 298.29944444
 999.         999.         999.         999.         999.
 999.         999.         999.         999.         999.        ]
[  0.           0.           7.58611111  26.35611111  39.88194444
  65.55972222  69.10388889  74.50333333  89.23666667  90.3925
  92.56166667  93.78972222  96.22166667 107.78777778 108.68583333
 108.72944444 116.73694444 117.98138889 122.36666667 134.06527778
 142.02027778 144.90888889 145.92166667 147.21666667 149.97416667
 150.59222222 152.58       153.33666667 159.78166667 174.99305556
 190.17666667 202.13416667 203.61111111 207.16361111 210.456

In [30]:
remove_index = []
for x in range(0,no_of_comb*4):    
    for y in range(0,3): 
        if reduction[x][y][max_quantity-1] == 0:
            remove_index.append(x)

print(remove_index)

[]


출력

In [31]:
import copy
final = copy.deepcopy(reduction)
print(final)

[[[2.62197222e+01 4.55669444e+01 5.20916667e+01 ... 9.99000000e+02
   9.99000000e+02 9.99000000e+02]
  [0.00000000e+00 0.00000000e+00 7.58611111e+00 ... 2.41203333e+02
   2.47965556e+02 2.58360000e+02]
  [7.50555556e+00 1.28319444e+01 2.06205556e+01 ... 1.38809722e+02
   1.40894444e+02 1.42445556e+02]]

 [[2.62197222e+01 4.55669444e+01 5.20916667e+01 ... 9.99000000e+02
   9.99000000e+02 9.99000000e+02]
  [0.00000000e+00 0.00000000e+00 7.58611111e+00 ... 2.41203333e+02
   2.47965556e+02 2.58360000e+02]
  [6.69722222e+00 1.34169444e+01 1.45730556e+01 ... 7.55280556e+01
   8.43711111e+01 9.93833333e+01]]

 [[2.62197222e+01 4.55669444e+01 5.20916667e+01 ... 9.99000000e+02
   9.99000000e+02 9.99000000e+02]
  [7.50555556e+00 1.28319444e+01 2.06205556e+01 ... 1.38809722e+02
   1.40894444e+02 1.42445556e+02]
  [6.69722222e+00 1.34169444e+01 1.45730556e+01 ... 7.55280556e+01
   8.43711111e+01 9.93833333e+01]]

 ...

 [[5.18611111e-01 2.60527778e+00 2.64305556e+00 ... 2.93855556e+01
   3.2546388

In [50]:
# ------------------------------------------------------------
# 결과 array data 화일 출력 - 1단계
# 72 X 3 = 216 Title (평가온도-평가전압) & data
# ------------------------------------------------------------

import openpyxl as op  #openpyxl 모듈 import
import os

censoring = copy.deepcopy(reduction)
            
os.chdir("P:\Intel 자동화 검증")
wb1 = op.Workbook()

ws1 = wb1.create_sheet("Full_comb_of_three_cond",0) #wb 객체를 통해 새로운 시트 생성
ws1 = wb1["Full_comb_of_three_cond"] #결과 출력용 Sheet로 설정하기

# title 출력

i=0
for x in range(0, no_of_comb*4):
    if x not in remove_index:
        ws1.cell(row = 1, column = i*7+1).value = 'Set '+str(i+1) 
        # 72 set 정보를 행(row=1)에 열을 바꾸면서 출력
        i += 1

i=1
for x in range(0, no_of_comb*4):
    if x not in remove_index:
        for y in range(0, 3):
            # print(x*3+y, title_array[x*3+y])
            ws1.cell(row = 2, column = i).value = title_array[x*3+y]  # 1행(row=1)에 열을 바꾸면서 출력
            ws1.cell(row = 2, column = i+1).value = 'Censor'+str(x*3+y+1) 
            i += 2
        i += 1
        
i=3 #행
j=1 #열
for x in range(0, no_of_comb*4):    
    if x not in remove_index: 
        for y in range(0,3): 
            for z in  range(0,max_quantity):
                if censoring[x][y][z] != 0: 
                    if censoring[x][y][z] == 999:                  
                        target = title_array[x*3+y]
                        censoring[x][y][z] = time[(column.index(target))]
                        ws1.cell(row = i, column=j).value = censoring[x][y][z]  
                        ws1.cell(row = i, column=j+1).value = 1 
                        # print(x, '-', y, censoring[x][y][z])
                    else:
                        ws1.cell(row = i, column=j).value = censoring[x][y][z]  
                        ws1.cell(row = i, column=j+1).value = 0 
                        # print(x, '-', y, censoring[x][y][z])  
                    i += 1  #행값 증가
            i = 3
            j += 2 # 열값 증가
        j += 1 # 3열당 한칸 뜀
i = 3
 
wb1.save("minitab_output1_test.xlsx") #해당 워크북(엑셀파일) 저장하기

In [401]:
# ------------------------------------------------------------
# 
# 2. 미니탭 'Temp Volt Time censor' 형식 출력
# ------------------------------------------------------------

import  openpyxl  as  op  #openpyxl 모듈 import
import os

os.chdir("P:\Intel 자동화 검증")

final = copy.deepcopy(reduction)

# wb1 = op.Workbook()
# wb1.save("censor_substitute1.xlsx") 

# # X path = r"P:\자동데이타생성"
# # X wb = op.load_workbook(path + "/test_result.xlsx")

wb1 = op.load_workbook("censor_substitute1.xlsx")

ws2 = wb1.create_sheet("Minitab_data2",1) #wb 객체를 통해 새로운 시트 생성
ws2 = wb1["Minitab_data2"] #결과 출력용 Sheet로 설정하기

# title 출력
i=0 
for x in range(0, no_of_comb*4):
    if x not in remove_index:
        ws2.cell(row = 1, column = i*5+1).value = 'Set '+str(i+1)+' : ' 
        # 72 set 정보를 행(row=1)에 열을 바꾸면서 출력
        ws2.cell(row = 1, column = i*5+2).value = title_array2[i]  
        ws2.cell(row = 2, column = i*5+1).value = 'Temp'+str(i+1)
        ws2.cell(row = 2, column = i*5+2).value = 'Vot'+str(i+1)
        ws2.cell(row = 2, column = i*5+3).value = 'Time'+str(i+1)
        ws2.cell(row = 2, column = i*5+4).value = 'Censor'+str(i+1)
        i += 1
    
title_array3 = np.reshape(title_array, (no_of_comb*4, -1))
# print(censoring)

i=3
j=1
for x in range(0, 1):    # no_of_comb*4
    if x not in remove_index:
        for y in range(0, 1):  # 3
            for z in  range(0, max_quantity):
                if final[x][y][z] == 999:
                    censor = 1
                    censor_temp = int(title_array3[x][y].split('-')[0])
                    censor_volt = float(title_array3[x][y].split('-')[1])
                    target = str(censor_temp)+'-'+str(censor_volt)
                    final[x][y][z] = time[(column.index(target))]
                                        
                    # print(censor_temp, censor_volt, censoring[x][y][z], 1)
                    ws2.cell(row = i, column=j).value = int(title_array3[x][y].split('-')[0])
                    ws2.cell(row = i, column=j+1).value = float(title_array3[x][y].split('-')[1])
                    ws2.cell(row = i, column=j+2).value = censoring[x][y][z]            # A열(Column=1)에 행을 바꾸면서 출력
                    ws2.cell(row = i, column=j+3).value = 1
                else:
                    # print(int(title_array3[x][y].split('-')[0]), float(title_array3[x][y].split('-')[1]), censoring[x][y][z], 0)
                    ws2.cell(row = i, column=j).value = int(title_array3[x][y].split('-')[0])
                    ws2.cell(row = i, column=j+1).value = float(title_array3[x][y].split('-')[1])
                    ws2.cell(row = i, column=j+2).value = censoring[x][y][z]            # A열(Column=1)에 행을 바꾸면서 출력
                    ws2.cell(row = i, column=j+3).value = 0                     # Censoring 판단 로직 추가 필요
                i += 1                    #행값 증가
        i = 3
        j += 5   



# for x in range(0,72):    
#     for y in range(0,3): 
#         for z in  range(0,40):
#             ws.cell(row = i, column=j).value = final[x][y][z]  #A열(Column=1)에 행을 바꾸면서 출력
#             i += 1  #행값 증가
#     i = 3
#     j += 5
 
# wb1.save("censor_substitute1.xlsx") #해당 워크북(엑셀파일) 저장하기

105 12.0 26.219722222222224 0
105 12.0 45.566944444444445 0
105 12.0 52.09166666666667 0
105 12.0 89.26722222222222 0
105 12.0 97.09027777777777 0
105 12.0 100.89444444444445 0
105 12.0 114.36333333333333 0
105 12.0 115.58055555555555 0
105 12.0 117.03194444444445 0
105 12.0 130.77277777777778 0
105 12.0 133.17138888888888 0
105 12.0 169.75805555555556 0
105 12.0 171.55138888888888 0
105 12.0 180.35722222222222 0
105 12.0 183.06222222222223 0
105 12.0 189.01472222222222 0
105 12.0 189.32861111111112 0
105 12.0 189.7211111111111 0
105 12.0 192.2163888888889 0
105 12.0 203.99444444444444 0
105 12.0 211.45638888888888 0
105 12.0 245.24444444444444 0
105 12.0 250.50722222222223 0
105 12.0 252.95138888888889 0
105 12.0 255.5688888888889 0
105 12.0 267.5283333333333 0
105 12.0 271.2522222222222 0
105 12.0 275.14666666666665 0
105 12.0 288.1411111111111 0
105 12.0 298.2994444444444 0
105 12.0 300.0 1
105 12.0 300.0 1
105 12.0 300.0 1
105 12.0 300.0 1
105 12.0 300.0 1
105 12.0 300.0 1
105 12.0

In [246]:
# value = test_time[0]
# print(value)
# print(type(float(title_array3[0][0].split('-')[0])), float(title_array3[0][0].split('-')[0]))
# print(np.where(temp, title_array3[0][0].split('-')[0]))
# , float(title_array3[x][y].split('-')[1]

<class 'float'> 105.0


In [339]:
# column ['105-12.0', '105-14.0', '105-16.0', '105-18.0', '115-12.0', '115-14.0', '115-16.0', '115-18.0']
ltoa0 = np.array(column)
print(ltoa0)
ltoa1 = np.array(test_temp)
print(ltoa1)
ltoa2 = np.array(test_volt)
print(type(ltoa2), ltoa2)

['105-12.0' '105-14.0' '105-16.0' '105-18.0' '115-12.0' '115-14.0'
 '115-16.0' '115-18.0']
['105' '115']
<class 'numpy.ndarray'> ['12.0' '14.0' '16.0' '18.0']


In [340]:
censor_temp = int(title_array3[0][0].split('-')[0])
censor_volt = float(title_array3[0][0].split('-')[1])
target = str(censor_temp)+'-'+str(censor_volt)
print(target)
# where = np.where(ltoa0 == target)
# print(type(where[0]), where[0], column.where)

print(column.index(target), time[(column.index(target))])

105-12.0
0 300.0


In [ ]:
#openpyxl

import  openpyxl  as  op  #openpyxl 모듈 import

# 신규 파일로 객체를 생성하는 경우
wb = op.Workbook() #새로운 워크북 객체 생성

ws = wb.create_sheet("new_sheet1") #wb 객체를 통해 새로운 시트 생성(시트명 : new_sheet1)
print(ws) #ws 객체 출력해보기

ws = wb.active #활성화되어있는 시트 설정
print(ws)

ws = wb["new_sheet1"] #신규 Sheet로 설정하기
print(ws)

ws_list = wb.sheetnames  #해당 Workbook의 시트 목록을 리스트로 저장
print(ws_list) #리스트 출력

for  sht  in  ws_list:
    ws = wb[sht] #Sheet 객체 생성
    print(ws) #객체 출력

#기존에 만들어져 있는 파일로 객체를 생성하는 경우
#path = r"C:\Users\Desktop\VS CODE\Project\practice\연습"
#wb = op.load_workbook(path + "/test.xlsx")

# Excel에서 data 읽기
#import  openpyxl  as  op  #openpyxl 모듈 import

# wb = op.load_workbook(r"test.xlsx") #워크북 객체 생성(파일명 : test.xlsx)
# ws = wb.active  #활성화 되어있는 시트 설정(시트명 : "업")

# #방법 1 : Sheet의 Cell 속성 사용하기
# data1 = ws.cell(row=1, column=2).value

# #방법 2 : 엑셀 인덱스(Range) 사용하기
# data2 = ws["B1"].value

# #위 결과 출력해보기
# print("cell(1,2) : ", data1)
# print('Range("B1"):', data2)

#wb.save("test_result.xlsx") #해당 워크북(엑셀파일) 저장하기
#wb.save(r"C:\Users\Desktop\VS CODE\openpyxl_test.xlsx") #절대 경로 지정

#wb.save(r"C:\Users\Desktop\VS CODE\openpyxl_test.xlsx")
#wb.save("openpyxl_test.xlsx")

In [ ]:

import openpyxl as op   #openpyxl 모듈 import
import os

os.chdir("P:\자동데이타생성")

#import xlwings as xw
#bk1 = xw.Book('output_test.xlsx')
#sh1 = bk1.sheets(1)
#df1_des = bk1.sheets(1).range('B3:M13').options(pd.DataFrame, index=False, header=False).value

wb = op.load_workbook("test.xlsx") #워크북 객체 생성(파일명 : test.xlsx)
ws = wb.active  #활성화 되어있는 시트 설정(시트명 : "업")

datalist = [2,4,8,16,32,64,128,256] #임의의 숫자 리스트 정의

i=1  # 행값을 바꾸기 위한 인덱스 정의

for  data  in  datalist:
    ws.cell(row = i, column=1).value = data  #A열(Column=1)에 행을 바꾸면서 입력
    i=i+1  #행값 증가

wb.save("result.xlsx")


In [ ]:
df2_des = pd.DataFrame(df2.iloc[0:8, :4].dropna(axis = 0, how = 'all').values)
df2_des

In [ ]:
column = df2.iloc[8].dropna(axis = 0, how = 'all').to_list()
print(column)


In [ ]:
# tab name 취출
test_cond_list = [bk1.sheets(x).name for x in range(2,14)]
#test_cond_list.sort()

print(test_cond_list)

In [ ]:
df2_data = pd.DataFrame(df2.iloc[9:49, :4].dropna(axis = 0, how = 'all').values, columns = column)
df2_data

In [ ]:
column_cut = df2_data.loc[0:39, 'FAILURE HOUR'].values
print(column_cut)

In [ ]:
import numpy as np

max_data =40
i = len(test_temp)
j = len(test_volt)
k = max_data

new_array= np.zeros((i, j, k))
new_array[0][0] = column_cut

print(new_array)

In [ ]:
ar1[1][0][0]

In [ ]:
import sys

from PyQt5.QtCore import QAbstractTableModel, Qt
from PyQt5.QtWidgets import QApplication, QMainWindow, QTableView


class PandasModel(QAbstractTableModel):
    def __init__(self, data):
        super().__init__()
        self._data = data

    def rowCount(self, index):
        # The length of the outer list.
        return len(self._data)

    def columnCount(self, index):
        # The following takes the first sub-list, and returns
        # the length (only works if all rows are an equal length)
        return len(self._data[0])

    def data(self, index, role=Qt.DisplayRole):
        if index.isValid():
            if role == Qt.DisplayRole or role == Qt.EditRole:
                value = self._data[index.row()][index.column()]
                return str(value)

    def setData(self, index, value, role):
        if role == Qt.EditRole:
            self._data[index.row()][index.column()] = value
            return True
        return False

    def flags(self, index):
        return Qt.ItemIsSelectable | Qt.ItemIsEnabled | Qt.ItemIsEditable


class MainWindow(QMainWindow):
    def __init__(self):
        super().__init__()

        self.table = QTableView()

        data = [
            [1, 9, 2],
            [1, 0, -1],
            [3, 5, 2],
            [3, 3, 2],
            [5, 8, 9],
        ]

        self.model = PandasModel(data)
        self.table.setModel(self.model)

        self.setCentralWidget(self.table)


app = QApplication(sys.argv)
window = MainWindow()
window.show()
app.exec_()


In [ ]:
# https://hleecaster.com/excel-crawling-with-python/

import os
path = "./files"
file_list = os.listdir(path)
print(file_list)

from openpyxl import load_workbook

results = []
for file_name_raw in file_list:
    file_name = "./files/" + file_name_raw
    wb = load_workbook(filename=file_name, data_only=True)
    ws = wb.active
    result = []
    result.append(file_name_raw)
    result.append(ws['C2'].value)
    result.append(ws['C3'].value)
    result.append(ws['E2'].value)
    result.append(ws['E3'].value)
    results.append(result)
print(results)

from openpyxl import Workbook
wb = Workbook()
ws = wb.active

for i in results:
    ws.append(i)
wb.save("results.xlsx")

In [ ]:
i=1
           
for x in range(0,216):
    print(i)
    if x%3 == 2:
        i += 2  # 3열에 구분열 1열씩 추가 
    else:
        i += 1  # 열값 증가

In [2]:
from PyQt5.QtCore import *
import pandas as pd


class pandasModel(QAbstractTableModel):
    def __init__(self, df=pd.DataFrame()):
        super().__init__()
        self.df = df

    def rowCount(self, parent=None):
        return self.df.shape[0]

    def columnCount(self, index=None):
        return self.df.shape[1]

    def data(self, index, role=Qt.DisplayRole):
        if not index.isValid() or role != Qt.DisplayRole:
            return QVariant()
        return str(self.df.iloc[index.row(), index.column()])

    def flags(self, index):
        return Qt.ItemIsEnabled | Qt.ItemIsSelectable | Qt.ItemIsEditable

    def setData(self, index, value, role):
        if not index.isValid():
            return QVariant()
        if role == Qt.DisplayRole or role == Qt.EditRole:
            self.df.iloc[index.row(), index.column()] = value
            self.dataChanged.emit(index, index)
            return True
        return QVariant()

    def headerData(self, section, orientation, role=Qt.DisplayRole):
        if role != Qt.DisplayRole:
            return QVariant()

        if orientation == Qt.Horizontal:

            return self.df.columns[section]
        elif orientation == Qt.Vertical:
            return str(self.df.index[section])

In [1]:
from PyQt5.QtWidgets import *
from PyQt5.QtGui import *
from PyQt5.QtCore import *
import os
import sys
import xlwings as xw
import pandas as pd

os.chdir("M:\DC-bias library_1771")
from main_wnd_intel import Ui_MainWindow

from PyQt5.QtCore import *
import pandas as pd


class pandasModel(QAbstractTableModel):
    def __init__(self, df=pd.DataFrame()):
        super().__init__()
        self.df = df

    def rowCount(self, parent=None):
        return self.df.shape[0]

    def columnCount(self, index=None):
        return self.df.shape[1]

    def data(self, index, role=Qt.DisplayRole):
        if not index.isValid() or role != Qt.DisplayRole:
            return QVariant()
        return str(self.df.iloc[index.row(), index.column()])

    def flags(self, index):
        return Qt.ItemIsEnabled | Qt.ItemIsSelectable | Qt.ItemIsEditable

    def setData(self, index, value, role):
        if not index.isValid():
            return QVariant()
        if role == Qt.DisplayRole or role == Qt.EditRole:
            self.df.iloc[index.row(), index.column()] = value
            self.dataChanged.emit(index, index)
            return True
        return QVariant()

    def headerData(self, section, orientation, role=Qt.DisplayRole):
        if role != Qt.DisplayRole:
            return QVariant()

        if orientation == Qt.Horizontal:

            return self.df.columns[section]
        elif orientation == Qt.Vertical:
            return str(self.df.index[section])
        
class Form(QMainWindow, Ui_MainWindow):
    def __init__(self):
        super().__init__()
        self.setupUi(self)
        self.actionOpen_2.triggered.connect(self.open_file)
        
    def open_file(self):   
        os.chdir("P:\자동데이타생성")
        bk1 = xw.Book('03W225_AI44B5O.xlsx')
        df1_data = bk1.sheets(1).range('B14').options(pd.DataFrame, index=False, header=False, expand='table').value
        
        max_data = 40
        show_data = df1_data
        column = ['125-12.0', '125-14.0', '125-16.0', '125-18.0', '135-12.0', '135-14.0', '135-16.0', '135-18.0', '145-12.0', '145-14.0', '145-16.0', '145-18.0']
        show_data.columns = column
        new_index = range(1, max_data+1)
        show_data.index = new_index
        self.make_tableLib(show_data)
        
        test_temp = ['125', '135', '145']
        test_volt = ['12.0', '14.0', '16.0', '18.0']
        testcond = pd.DataFrame(columns = test_volt, index = test_temp)
        show_cond = testcond.fillna('V')
        self.make_tableConst(show_cond)

    def make_tableLib(self, df):
        model = pandasModel(df)
        self.tableLib.setModel(model)
        self.tableLib.resizeColumnsToContents()
        self.tableLib.horizontalHeader().setSectionResizeMode(QHeaderView.Stretch)
        self.tableLib.verticalHeader().setSectionResizeMode(QHeaderView.Stretch)
    
    def make_tableConst(self, df):
        model = pandasModel(df)
        self.tableConst.setModel(model)
        self.tableConst.resizeColumnsToContents()
        self.tableConst.horizontalHeader().setSectionResizeMode(QHeaderView.Stretch)
        self.tableConst.verticalHeader().setSectionResizeMode(QHeaderView.Stretch)
        
app = QApplication(sys.argv)
w = Form()
w.show()

app.exec_()

0