In [10]:
# [파이썬/업무자동화] 엑셀 전체 셀 내용 중 특정 문자만 변경/제거하기
# https://ybworld.tistory.com/112

import openpyxl as op
import numpy as np

#path는 대상이 되는 엑셀파일의 절대 경로
def corretion(path : str):
    #openpyxl 워크북 정의
    wb = op.load_workbook(path)
    #워크북의 활성화된 시트를 객체로 정의
    ws = wb["L_AI9MP1U_2"]
    # #시트 탭 색깔 변경(하늘색)
    # ws.sheet_properties.tabColor = '#008000'


    #해당 시트의 마지막 열, 마지막 행 
    column_max = ws.max_column
    row_max = ws.max_row
    no_of_comb = int(input("Set 수는? : "))
    print(column_max, row_max, no_of_comb)

    temp = np.zeros((no_of_comb, 6))
    volt = np.zeros((no_of_comb, 6))
    life = np.zeros((no_of_comb, 4))
    
    #열마다 행을 for loop문 진행
    for col_num in range(2, 4):
        for row_num in range(1, row_max+1):
            for x in range(0, no_of_comb):
                #tempstr : cell값이 문자열이 아닌 경우를 감안하여 str로 바꿔줌
                tempstr = str(ws.cell(row = row_num, column = col_num).value)
                tempstr2 = str(ws.cell(row = row_num+1, column = col_num).value)
#                 if (tempstr == 'Temp'+str(x+1) and tempstr2 == 'Vot'+str(x+1)):
#                     print (col_num, row_num, tempstr, tempstr2)
                       
                if tempstr == 'Temp'+str(x+1):
                    if tempstr2 == 'Vot'+str(x+1):
                        for y in range(0, 6):
                            temp[x][y] = ws.cell(row = row_num, column = col_num+y+1).value
                            volt[x][y] = ws.cell(row = row_num+1, column = col_num+y+1).value
                    elif tempstr2 == '0.001':   
                        for y in range(0, 4):
                            life[x][y] = ws.cell(row = row_num+1, column = col_num+y+3).value
               
             
                    
                                
    print("\n")                                              
    print(temp, "\n", volt, "\n", life)

    print("==============================    Extraction Result   =============================") 
    print(" Set No              Temp Accel_Low             Volt Accel_Low             Life_Low")
    for i in range(0, no_of_comb):
        print('Set'+str(i+1), temp[i][4], abs(volt[i][5]), life[i][2]/8750)
        
        
        
#             #문자열 함수 replace 사용(,를 빈칸으로)
#             data = tempstr.replace(",","")
#             #빈 셀의 경우 None이라는 문자열 타입이므로 제외하고 데이터 입력
#             if data != "None":
#                 ws.cell(row = row_num, column = col_num).value = data   
                     
            #원하는 문자열이면 이후 필요한 cell 내용 추출
            
            

    #저장
#     wb.save("correction_result.xlsx")

if __name__ == "__main__":
#     path = input("화일경로는 ? \n Ex) r'P:\자동데이타생성\쎄션 데이터 추출.xlsx' : ")
    path = r"P:/Intel 자동화 검증/03W105MR3_AI9MP1U_3X4_2_session.xlsx"

    #함수 실행
    corretion(path)

27 3430 72


[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]


In [13]:
import openpyxl as op
import numpy as np

#path는 대상이 되는 엑셀파일의 절대 경로
def corretion(path : str):
    #openpyxl 워크북 정의
    wb = op.load_workbook(path)
    #워크북의 '동일성' 시트를 객체로 정의
    ws = wb["L_AI9MP1U_2"]

    #해당 시트의 마지막 열, 마지막 행 
    column_max = ws.max_column
    row_max = ws.max_row
    no_of_comb = int(input("Set 수는? : "))
    print(column_max, row_max, "\n")

    # kai = np.zeros((no_of_comb, 3))
    # cond = np.array((no_of_comb, 3))
    
    #열마다 행을 for loop문 진행
    for col_num in range(2, 3):
        for row_num in range(1, row_max+1):
            for x in range(0, no_of_comb):
                tempstr = str(ws.cell(row = row_num, column = col_num).value)
                tempstr2 = str(ws.cell(row = row_num+1, column = col_num).value)
                
                temp = []
                volt = []
                life = []
                if tempstr == 'Temp'+str(x+1):
                    if tempstr2 == 'Volt'+str(x+1):
                        for y in range(0, 6):
                            temp.append(ws.cell(row = row_num, column = col_num+y+1).value)
                            volt.append(ws.cell(row = row_num+1, column = col_num+y+1).value)
                    elif tempstr2 == '0.001':   
                        for y in range(0, 4):
                            life.append(ws.cell(row = row_num+1, column = col_num+y+3).value)
                
                    total_info = temp + volt + life
                    # ws.cell(row = row_num+2, column = 12, value = total_info)
                    print(total_info)
            
        #저장
        # wb.save(path)

if __name__ == "__main__":
    path = r"P:/Intel 자동화 검증/03W105MR3_AI9MP1U_3X4_2_session.xlsx"

    #함수 실행
    corretion(path)

32 3430 

[1.47185, 0.172762, 8.52, 0, 1.18768, 1.75602, -2.34794, 0.916075, -2.56, 0.01, -3.85474, -0.841127]
[1.70896, 0.15261, 11.2, 0, 1.45794, 1.95998, -2.24177, 0.79006, -2.84, 0.005, -3.54131, -0.942241]
[1.47614, 0.177616, 8.31, 0, 1.18399, 1.76829, -3.564, 0.900453, -3.96, 0, -5.04512, -2.08289]
[1.70896, 0.154235, 11.08, 0, 1.45526, 1.96265, -3.564, 0.764527, -4.66, 0, -4.82154, -2.30647]
[1.49192, 0.195381, 7.64, 0, 1.17055, 1.8133, -4.80479, 0.547317, -8.78, 0, -5.70505, -3.90454]
[1.5244, 0.197526, 7.72, 0, 1.1995, 1.84931, -4.80353, 0.545895, -8.8, 0, -5.70145, -3.90561]
[1.4928, 0.196354, 7.6, 0, 1.16982, 1.81577, -4.89406, 0.536455, -9.12, 0, -5.77645, -4.01167]
[1.5244, 0.193999, 7.86, 0, 1.2053, 1.8435, -4.89406, 0.52291, -9.36, 0, -5.75417, -4.03395]
[1.47536, 0.176735, 8.35, 0, 1.18466, 1.76607, -4.50521, 0.34673, -12.99, 0, -5.07553, -3.93489]
[0.82819, 0.179811, 4.61, 0, 0.532428, 1.12395, -4.50585, 0.347485, -12.97, 0, -5.07741, -3.93429]
[1.49417, 0.197898, 7.55

In [12]:
# session 화일 추출 위치 마킹

import openpyxl as op
import numpy as np

#path는 대상이 되는 엑셀파일의 절대 경로
def corretion(path : str):
    #openpyxl 워크북 정의
    wb = op.load_workbook(path)
    #워크북의 '동일성' 시트를 객체로 정의
    ws = wb["L_AI9MP1U_2"]

    #해당 시트의 마지막 열, 마지막 행 
    column_max = ws.max_column
    row_max = ws.max_row
    no_of_comb = int(input("Set 수는? : "))
    print(column_max, row_max, "\n")

    # kai = np.zeros((no_of_comb, 3))
    # cond = np.array((no_of_comb, 3))
    
    #열마다 행을 for loop문 진행
    for col_num in range(2, 3):
        for row_num in range(1, row_max+1):
            for x in range(0, no_of_comb):
                tempstr = str(ws.cell(row = row_num, column = col_num).value)
                tempstr2 = str(ws.cell(row = row_num+1, column = col_num).value)
                
                temp = []
                volt = []
                life = []
                if tempstr == 'Temp'+str(x+1):
                    ws.cell(row = row_num, column = col_num-1, value = 'V')
                    ws.cell(row = row_num+1, column = col_num-1, value = 'V')
                    if tempstr2 == 'Volt'+str(x+1):
                       
                        for y in range(0, 6):
                            temp.append(ws.cell(row = row_num, column = col_num+y+1).value)
                            volt.append(ws.cell(row = row_num+1, column = col_num+y+1).value)
                    elif tempstr2 == '0.001':   
                        for y in range(0, 4):
                            life.append(ws.cell(row = row_num+1, column = col_num+y+3).value)
                
                    total_info = temp + volt + life
                    # ws.cell(row = row_num+2, column = 12, value = total_info)
                    print(total_info)
            
        #저장
        # wb.save(path)

if __name__ == "__main__":
    path = r"P:/Intel 자동화 검증/03W105MR3_AI9MP1U_3X4_2_session.xlsx"

    #함수 실행
    corretion(path)

32 3430 

[1.47185, 0.172762, 8.52, 0, 1.18768, 1.75602, -2.34794, 0.916075, -2.56, 0.01, -3.85474, -0.841127]
[1.70896, 0.15261, 11.2, 0, 1.45794, 1.95998, -2.24177, 0.79006, -2.84, 0.005, -3.54131, -0.942241]
[1.47614, 0.177616, 8.31, 0, 1.18399, 1.76829, -3.564, 0.900453, -3.96, 0, -5.04512, -2.08289]
[1.70896, 0.154235, 11.08, 0, 1.45526, 1.96265, -3.564, 0.764527, -4.66, 0, -4.82154, -2.30647]
[1.49192, 0.195381, 7.64, 0, 1.17055, 1.8133, -4.80479, 0.547317, -8.78, 0, -5.70505, -3.90454]
[1.5244, 0.197526, 7.72, 0, 1.1995, 1.84931, -4.80353, 0.545895, -8.8, 0, -5.70145, -3.90561]
[1.4928, 0.196354, 7.6, 0, 1.16982, 1.81577, -4.89406, 0.536455, -9.12, 0, -5.77645, -4.01167]
[1.5244, 0.193999, 7.86, 0, 1.2053, 1.8435, -4.89406, 0.52291, -9.36, 0, -5.75417, -4.03395]
[1.47536, 0.176735, 8.35, 0, 1.18466, 1.76607, -4.50521, 0.34673, -12.99, 0, -5.07553, -3.93489]
[0.82819, 0.179811, 4.61, 0, 0.532428, 1.12395, -4.50585, 0.347485, -12.97, 0, -5.07741, -3.93429]
[1.49417, 0.197898, 7.55

In [ ]:
import random
import openpyxl as op

#가상 엑셀파일을 생성할 주소
path = r"M:\Test"
#몇개 생성할것 인가?
n = 10

#random 모듈 및 openpyxl 통한 가상의 엑셀파일 및 랜덤 데이터 생성
for i in range(1, n+1):

#     wb = op.Workbook()
#     ws = wb.active
#     #random모듈의 randrage 함수를 통한 랜덤 숫자 data 생성 및 엑셀입력
#     for row_num in range(1,11):
#         ws.cell(row=row_num, column=1).value = str(row_num)+"번째 data"
#         ws.cell(row=row_num, column=2).value = random.randrange(1,100)
    
#     #엑셀 파일 저장
#     wb.save(path+"\"+str(i)+".xlsx")
    print(path+"\")   

SyntaxError: EOL while scanning string literal (<ipython-input-79-6e490bcc89af>, line 21)

In [ ]:
import openpyxl as op
import os


#셀주소를 직접 입력받아 저장하는 함수
def saveCellAddress()->list:
    
    num = int(input('몇개 입력받을거야? : '))
    #엑셀 셀 주소를 저장하기 위한 빈 리스트 생성
    save_cell = []
    #입력받을 숫자만큼 데이터를 받고 for문 실행
    for i in range(1,num+1):
        print(str(i)+"번째 입력 : ")
        cell = str(input('첫번째 셀 주소 입력 ex)A1,B1: '))
        save_cell.append(cell)
    print(save_cell)
    
    return save_cell

#엑셀 파일 있는 주소, Cell 주소 입력받아 정해진 위치 값들 딕셔너리로 저장
def saveData(path : str, cell_list : list):
    excellist = os.listdir(path) #설정한 폴더경로에 있는 엑셀파일명을 리스트화
    dic = {} #빈 딕셔너리 생성
    
    #cell 주소당 빈 딕셔너리 생성
    for cell in cell_list:
        dic[cell] = ''

    #설정한 cell 주소에 대해 모든 엑셀파일을 루프로 돌면서 데이터를 저장. 
    for cell in cell_list:
        templist = [] # 빈 임시 리스트 생성
        for file in excellist: #엑셀파일 list를 루프로 실행
            wb = op.load_workbook(path + "/" + file)
            ws = wb.active
            templist.append(ws[cell].value) #빈 임시 리스트에 필요한 값을 가져옴.
        dic[cell] = templist #임시 리스트를 딕셔너리화(key : cell주소, value : 값 리스트)
    print(dic)
   
    return dic

#딕셔너리를 매개변수로 입력받아 새로운 엑셀파일에 취합하는 함수
def writeExcel(dic):
    #새로운 엑셀파일 생성
    wb = op.Workbook()
    ws = wb.active
    
    #엑셀파일 입력을 위한 reference 
    row_num=1 #행
    col_num=1 #열

    #딕셔너리 key값을 활용하여 for문 진행
    for key in dic.keys():
        #각 key값에 따른 리스트를 다시 for문 진행
        for data in dic[key]:            
            ws.cell(row=row_num, column = col_num).value = data # 입력
            row_num = row_num + 1 #행값 증가
        col_num = col_num+1 #열값 증가
        row_num = 1 #각 cell주소에 대한 data 입력이 끝나면 행=1로 초기화
    
    #저장
    wb.save("dic_Result.xlsx")
    print("생성 완료")

if __name__ == "__main__":

    path = r"C:\Users\Yongbeom Jeong\Desktop\VS CODE\Project\collect_Data\random"
    cell = saveCellAddress()
    dic = saveData(path, cell)
    writeExcel(dic)
        

